-- Create a small employee table if you don’t already have one
CREATE TABLE EMPLOYEE_MASTER (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(100) NOT NULL
);

INSERT INTO EMPLOYEE_MASTER VALUES (101, 'John Doe');
INSERT INTO EMPLOYEE_MASTER VALUES (102, 'Jane Smith');
COMMIT;
